version: '3'
services:
    php:
        container_name: php
        build: .
        image: php
        ports:
            - "9000:9000"
        command: dockerize -wait tcp://database:3306 -timeout 30s ./symfony.sh
        volumes:
            - .:/var/www/code
        depends_on:
            - redis
            - database
        networks:
            - api
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/code
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - redis
            - database
        networks:
            - api
    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - "6379:6379"
        networks:
            - api
    mongo:
        image: mongo:latest
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: dfe4da18
        ports:
            - "27017:27017"
        volumes:
            - ./docker/mongo:/data/db
        networks:
            - api
    database:
        container_name: database
        image: mysql:latest
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: dfe4da18
            MYSQL_DATABASE: api
            MYSQL_USER: giovane
            MYSQL_PASSWORD: giovane
        ports:
            - '3306:3306'
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - api
networks:
    api:
        name: api
        driver: bridge
